"""
Generate Model V2 Feature Matrix CSV - Revision 1B
Reflects decoupled multi-model architecture (Hard CVD Primary, Diabetes Secondary, Hypertension Secondary)
with strict per-model leakage boundaries, Mode A/B classification, and ICMR compatibility.
"""

import os
import pandas as pd
from pathlib import Path

WORKSPACE_ROOT = Path(__file__).resolve().parents[3]
AUDIT_OUTPUT_DIR = WORKSPACE_ROOT / "backend" / "ml" / "data" / "interim" / "audit"

os.makedirs(AUDIT_OUTPUT_DIR, exist_ok=True)

matrix_data = [
    # MODE A: Baseline Non-Invasive Predictors (Demographics, Anthropometrics, Vitals, Lifestyle)
    {
        "feature_name": "age",
        "human_name": "Age (years)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "DEMO_L.xpt",
        "variable": "RIDAGEYR",
        "type": "Numeric",
        "coverage": "100.0% (N=7,809 adults)",
        "mode": "Mode A & B",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "v4 (Age)",
        "notes": "Direct numeric match. Top-coded at 80 years in NHANES. Allowed in CVD, Diabetes, and HTN models."
    },
    {
        "feature_name": "gender",
        "human_name": "Sex / Gender",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "DEMO_L.xpt",
        "variable": "RIAGENDR",
        "type": "Categorical",
        "coverage": "100.0% (N=7,809 adults)",
        "mode": "Mode A & B",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "v5 (Sex)",
        "notes": "Exact coding match: 1=Male, 2=Female. Allowed in all models."
    },
    {
        "feature_name": "education_level",
        "human_name": "Education Level",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "DEMO_L.xpt",
        "variable": "DMDEDUC2",
        "type": "Categorical",
        "coverage": "99.9% (N=7,802 adults)",
        "mode": "Mode A & B",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "v6 (Education)",
        "notes": "Harmonizable into 3 tiers (Low/Mid/High). Allowed in all models."
    },
    {
        "feature_name": "poverty_income_ratio",
        "human_name": "Poverty-Income Ratio (PIR)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "DEMO_L.xpt",
        "variable": "INDFMPIR",
        "type": "Numeric",
        "coverage": "85.9% (N=6,707 adults)",
        "mode": "Mode A & B",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "v24 (SLI Index)",
        "notes": "Socioeconomic status proxy; median imputable. Allowed in all models."
    },
    {
        "feature_name": "bmi",
        "human_name": "Body Mass Index (kg/m²)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "BMX_L.xpt",
        "variable": "BMXBMI",
        "type": "Numeric",
        "coverage": "76.5% (N=5,970 adults)",
        "mode": "Mode A & B",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "v8 (BMI) / v40 (Obesity)",
        "notes": "Continuous float. Standard CDC cutoff for NHANES; Asian Indian cutoff (BMI>=25) used for ICMR evaluation."
    },
    {
        "feature_name": "waist_circumference",
        "human_name": "Waist Circumference (cm)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "BMX_L.xpt",
        "variable": "BMXWAIST",
        "type": "Numeric",
        "coverage": "73.8% (N=5,765 adults)",
        "mode": "Mode A & B",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "v9 (Waist) / v39 (Abdominal Obesity)",
        "notes": "Continuous float. Standard tape measurement. South Asian cutoffs (>=90M, >=80F) used for ICMR evaluation."
    },
    {
        "feature_name": "systolic_bp",
        "human_name": "Mean Systolic Blood Pressure (mmHg)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "BPXO_L.xpt",
        "variable": "BPXOSY1..3 mean",
        "type": "Numeric",
        "coverage": "72.4% (N=5,654 adults)",
        "mode": "Mode A & B",
        "leakage_status": "Safe for CVD & Diabetes Models; PROHIBITED in Hypertension Model",
        "icmr_equivalent": "v10 (Systolic BP)",
        "notes": "Mean of 3 oscillometric readings. Allowed as predictor for CVD and Diabetes models; PROHIBITED in HTN Model."
    },
    {
        "feature_name": "diastolic_bp",
        "human_name": "Mean Diastolic Blood Pressure (mmHg)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "BPXO_L.xpt",
        "variable": "BPXODI1..3 mean",
        "type": "Numeric",
        "coverage": "72.4% (N=5,654 adults)",
        "mode": "Mode A & B",
        "leakage_status": "Safe for CVD & Diabetes Models; PROHIBITED in Hypertension Model",
        "icmr_equivalent": "v11 (Diastolic BP)",
        "notes": "Mean of 3 oscillometric readings. Allowed as predictor for CVD and Diabetes models; PROHIBITED in HTN Model."
    },
    {
        "feature_name": "resting_pulse",
        "human_name": "Resting Heart Rate (bpm)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "BPXO_L.xpt",
        "variable": "BPXOPLS1..3 mean",
        "type": "Numeric",
        "coverage": "72.4% (N=5,654 adults)",
        "mode": "Mode A & B",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "Not present in ICMR sample",
        "notes": "Mean resting pulse; clean replacement for legacy synthetic HRV features. Allowed in all models."
    },
    {
        "feature_name": "smoking_status",
        "human_name": "Smoking Status",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "SMQ_L.xpt",
        "variable": "SMQ020 / SMQ040",
        "type": "Categorical",
        "coverage": "88.7% (N=6,926 adults)",
        "mode": "Mode A & B",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "v25 (Smoking) / v27 (Any Tobacco)",
        "notes": "Recode to 0=Never, 1=Former, 2=Current. Allowed in all models."
    },
    {
        "feature_name": "alcohol_frequency",
        "human_name": "Alcohol Consumption Frequency",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "ALQ_L.xpt",
        "variable": "ALQ121 / ALQ111",
        "type": "Categorical",
        "coverage": "81.9% (N=6,397 adults)",
        "mode": "Mode A & B",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "v28 (Alcohol)",
        "notes": "Recode to 0=Never, 1=Former, 2=Current. Allowed in all models."
    },
    {
        "feature_name": "physical_activity_level",
        "human_name": "Overall Physical Activity Level",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "PAQ_L.xpt",
        "variable": "PAD790Q / PAD810Q",
        "type": "Categorical",
        "coverage": "89.1% (N=6,957 adults)",
        "mode": "Mode A & B",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "v32 (Overall Activity)",
        "notes": "Recode to WHO GPAQ 3 tiers: 1=High, 2=Moderate, 3=Low. Allowed in all models."
    },
    {
        "feature_name": "sedentary_minutes",
        "human_name": "Sedentary Duration (min/day)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "PAQ_L.xpt",
        "variable": "PAD680",
        "type": "Numeric",
        "coverage": "88.9% (N=6,944 adults)",
        "mode": "Mode A & B",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "v29 (Work Activity Sedentary proxy)",
        "notes": "Continuous daily sitting minutes. Allowed in all models."
    },

    # MODE B: Laboratory-Enhanced Predictors
    {
        "feature_name": "hba1c",
        "human_name": "Glycohemoglobin (HbA1c %)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "GHB_L.xpt",
        "variable": "LBXGH",
        "type": "Numeric",
        "coverage": "70.4% (N=5,498 adults)",
        "mode": "Mode B Only",
        "leakage_status": "Safe for CVD & HTN Models; PROHIBITED in Diabetes Model",
        "icmr_equivalent": "v36 (Diabetes flag)",
        "notes": "Tier 1 routine blood test. Gold standard glycemic biomarker. Allowed in CVD & HTN models; PROHIBITED in Diabetes Model."
    },
    {
        "feature_name": "fasting_glucose",
        "human_name": "Fasting Plasma Glucose (mg/dL)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "GLU_L.xpt",
        "variable": "LBXGLU",
        "type": "Numeric",
        "coverage": "41.1% (N=3,210 adults)",
        "mode": "Mode B Only",
        "leakage_status": "Safe for CVD & HTN Models; PROHIBITED in Diabetes Model",
        "icmr_equivalent": "v36 (Diabetes flag)",
        "notes": "Tier 1 routine glucose test (Fasting subsample). Allowed in CVD & HTN models; PROHIBITED in Diabetes Model."
    },
    {
        "feature_name": "total_cholesterol",
        "human_name": "Total Cholesterol (mg/dL)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "TCHOL_L.xpt",
        "variable": "LBXTC",
        "type": "Numeric",
        "coverage": "70.4% (N=5,498 adults)",
        "mode": "Mode B Only",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "v41 (Dyslipidemia flag)",
        "notes": "Tier 1 routine lipid panel test. Allowed in CVD, Diabetes, and HTN models."
    },
    {
        "feature_name": "hdl_cholesterol",
        "human_name": "Direct HDL-Cholesterol (mg/dL)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "HDL_L.xpt",
        "variable": "LBDHDD",
        "type": "Numeric",
        "coverage": "70.4% (N=5,498 adults)",
        "mode": "Mode B Only",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "v41 (Dyslipidemia flag)",
        "notes": "Tier 1 routine lipid panel test. Allowed in CVD, Diabetes, and HTN models."
    },
    {
        "feature_name": "triglycerides",
        "human_name": "Serum Triglycerides (mg/dL)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "TRIGLY_L.xpt",
        "variable": "LBXTLG",
        "type": "Numeric",
        "coverage": "41.1% (N=3,210 adults)",
        "mode": "Mode B Only",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "v41 (Dyslipidemia flag)",
        "notes": "Tier 2 lipid test (Fasting subsample). Allowed in all models."
    },
    {
        "feature_name": "ldl_cholesterol",
        "human_name": "Calculated LDL-Cholesterol (mg/dL)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "TRIGLY_L.xpt",
        "variable": "LBDLDL",
        "type": "Numeric",
        "coverage": "40.6% (N=3,172 adults)",
        "mode": "Mode B Only",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "v41 (Dyslipidemia flag)",
        "notes": "Tier 2 lipid test (Fasting subsample; Friedewald/Martin-Hopkins equation). Allowed in all models."
    },
    {
        "feature_name": "serum_creatinine",
        "human_name": "Serum Creatinine (mg/dL)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "BIOPRO_L.xpt",
        "variable": "LBXSCR",
        "type": "Numeric",
        "coverage": "70.4% (N=5,498 adults)",
        "mode": "Mode B Only",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "Not present in ICMR sample",
        "notes": "Tier 1 routine renal panel test. Used for eGFR (CKD-EPI equation). Allowed in all models."
    },
    {
        "feature_name": "blood_urea_nitrogen",
        "human_name": "Blood Urea Nitrogen (BUN mg/dL)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "BIOPRO_L.xpt",
        "variable": "LBXSBU",
        "type": "Numeric",
        "coverage": "70.4% (N=5,498 adults)",
        "mode": "Mode B Only",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "Not present in ICMR sample",
        "notes": "Tier 1 routine renal clearance & cardiorenal strain marker. Allowed in all models."
    },
    {
        "feature_name": "serum_uric_acid",
        "human_name": "Serum Uric Acid (mg/dL)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "BIOPRO_L.xpt",
        "variable": "LBXSUA",
        "type": "Numeric",
        "coverage": "70.4% (N=5,498 adults)",
        "mode": "Mode B Only",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "Not present in ICMR sample",
        "notes": "Tier 2 metabolic syndrome & endothelial dysfunction marker. Allowed in all models."
    },
    {
        "feature_name": "alt_enzyme",
        "human_name": "Alanine Aminotransferase (ALT U/L)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "BIOPRO_L.xpt",
        "variable": "LBXSATSI",
        "type": "Numeric",
        "coverage": "70.4% (N=5,498 adults)",
        "mode": "Mode B Only",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "Not present in ICMR sample",
        "notes": "Tier 2 liver function & steatotic liver disease indicator. Allowed in all models."
    },
    {
        "feature_name": "ast_enzyme",
        "human_name": "Aspartate Aminotransferase (AST U/L)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "BIOPRO_L.xpt",
        "variable": "LBXSASSI",
        "type": "Numeric",
        "coverage": "70.4% (N=5,498 adults)",
        "mode": "Mode B Only",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "Not present in ICMR sample",
        "notes": "Tier 2 liver function & cellular injury marker. Allowed in all models."
    },
    {
        "feature_name": "hemoglobin",
        "human_name": "Hemoglobin (g/dL)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "CBC_L.xpt",
        "variable": "LBXHGB",
        "type": "Numeric",
        "coverage": "73.1% (N=5,708 adults)",
        "mode": "Mode B Only",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "Not present in ICMR sample",
        "notes": "Tier 1 routine CBC test. Anemia detection & cardiac stressor. Allowed in all models."
    },
    {
        "feature_name": "wbc_count",
        "human_name": "White Blood Cell Count (10³/µL)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "CBC_L.xpt",
        "variable": "LBXWBCSI",
        "type": "Numeric",
        "coverage": "73.1% (N=5,708 adults)",
        "mode": "Mode B Only",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "Not present in ICMR sample",
        "notes": "Tier 1 routine CBC test. Low-grade systemic inflammation marker. Allowed in all models."
    },
    {
        "feature_name": "platelet_count",
        "human_name": "Platelet Count (10³/µL)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "CBC_L.xpt",
        "variable": "LBXPLTSI",
        "type": "Numeric",
        "coverage": "73.1% (N=5,708 adults)",
        "mode": "Mode B Only",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "Not present in ICMR sample",
        "notes": "Tier 2 routine CBC test. Thrombotic profile indicator. Allowed in all models."
    },
    {
        "feature_name": "rdw",
        "human_name": "Red Cell Distribution Width (%)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "CBC_L.xpt",
        "variable": "LBXRDW",
        "type": "Numeric",
        "coverage": "73.1% (N=5,708 adults)",
        "mode": "Mode B Only",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "Not present in ICMR sample",
        "notes": "Tier 2 routine CBC test. Independent cardiovascular mortality predictor. Allowed in all models."
    },
    {
        "feature_name": "serum_albumin",
        "human_name": "Serum Albumin (g/dL)",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "BIOPRO_L.xpt",
        "variable": "LBXSAL",
        "type": "Numeric",
        "coverage": "70.4% (N=5,498 adults)",
        "mode": "Mode B Only",
        "leakage_status": "Safe Predictor (All Models)",
        "icmr_equivalent": "Not present in ICMR sample",
        "notes": "Tier 2 routine metabolic panel marker. Nutritional & inflammatory status. Allowed in all models."
    },

    # TARGET & PROHIBITED LEAKAGE VARIABLES (Strictly Excluded per Model)
    {
        "feature_name": "mcq160b_chf",
        "human_name": "Congestive Heart Failure Diagnosis",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "MCQ_L.xpt",
        "variable": "MCQ160B",
        "type": "Binary",
        "coverage": "99.4% (N=7,764 adults)",
        "mode": "Excluded (Target Component)",
        "leakage_status": "PROHIBITED (Defines Hard CVD Target)",
        "icmr_equivalent": "v35 (Family Heart Disease)",
        "notes": "Target-defining variable for Hard CVD Classifier. FORBIDDEN as predictor in all models."
    },
    {
        "feature_name": "mcq160c_chd",
        "human_name": "Coronary Heart Disease Diagnosis",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "MCQ_L.xpt",
        "variable": "MCQ160C",
        "type": "Binary",
        "coverage": "99.4% (N=7,764 adults)",
        "mode": "Excluded (Target Component)",
        "leakage_status": "PROHIBITED (Defines Hard CVD Target)",
        "icmr_equivalent": "v35 (Family Heart Disease)",
        "notes": "Target-defining variable for Hard CVD Classifier. FORBIDDEN as predictor in all models."
    },
    {
        "feature_name": "mcq160d_angina",
        "human_name": "Angina Pectoris Diagnosis",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "MCQ_L.xpt",
        "variable": "MCQ160D",
        "type": "Binary",
        "coverage": "99.4% (N=7,764 adults)",
        "mode": "Excluded (Target Component)",
        "leakage_status": "PROHIBITED (Defines Hard CVD Target)",
        "icmr_equivalent": "v35 (Family Heart Disease)",
        "notes": "Target-defining variable for Hard CVD Classifier. FORBIDDEN as predictor in all models."
    },
    {
        "feature_name": "mcq160e_mi",
        "human_name": "Heart Attack (MI) Diagnosis",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "MCQ_L.xpt",
        "variable": "MCQ160E",
        "type": "Binary",
        "coverage": "99.4% (N=7,764 adults)",
        "mode": "Excluded (Target Component)",
        "leakage_status": "PROHIBITED (Defines Hard CVD Target)",
        "icmr_equivalent": "v35 (Family Heart Disease)",
        "notes": "Target-defining variable for Hard CVD Classifier. FORBIDDEN as predictor in all models."
    },
    {
        "feature_name": "mcq160f_stroke",
        "human_name": "Stroke Diagnosis",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "MCQ_L.xpt",
        "variable": "MCQ160F",
        "type": "Binary",
        "coverage": "99.4% (N=7,764 adults)",
        "mode": "Excluded (Target Component)",
        "leakage_status": "PROHIBITED (Defines Hard CVD Target)",
        "icmr_equivalent": "v35 (Family Heart Disease)",
        "notes": "Target-defining variable for Hard CVD Classifier. FORBIDDEN as predictor in all models."
    },
    {
        "feature_name": "diq010_dm_diag",
        "human_name": "Self-Reported Diabetes Diagnosis",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "DIQ_L.xpt",
        "variable": "DIQ010",
        "type": "Categorical",
        "coverage": "100.0% (N=7,809 adults)",
        "mode": "Excluded (Target Component)",
        "leakage_status": "PROHIBITED in Diabetes Model",
        "icmr_equivalent": "v36 (Diabetes flag)",
        "notes": "Target-defining variable for Diabetes Classifier. FORBIDDEN in Diabetes Model."
    },
    {
        "feature_name": "bpq020_htn_diag",
        "human_name": "Self-Reported Hypertension Diagnosis",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "BPQ_L.xpt",
        "variable": "BPQ020",
        "type": "Categorical",
        "coverage": "99.9% (N=7,800 adults)",
        "mode": "Excluded (Target Component)",
        "leakage_status": "PROHIBITED in Hypertension Model",
        "icmr_equivalent": "v38 (Hypertension flag)",
        "notes": "Target-defining variable for Hypertension Classifier. FORBIDDEN in HTN Model."
    },
    {
        "feature_name": "diq050_insulin",
        "human_name": "Taking Insulin",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "DIQ_L.xpt",
        "variable": "DIQ050",
        "type": "Binary",
        "coverage": "100.0% (N=7,809 adults)",
        "mode": "Excluded (Post-Outcome Treatment)",
        "leakage_status": "PROHIBITED in Diabetes Model",
        "icmr_equivalent": "v36 (Diabetes flag)",
        "notes": "Post-outcome drug treatment flag. FORBIDDEN in Diabetes Model."
    },
    {
        "feature_name": "diq070_dm_pills",
        "human_name": "Taking Diabetes Pills",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "DIQ_L.xpt",
        "variable": "DIQ070",
        "type": "Binary",
        "coverage": "100.0% (N=7,809 adults)",
        "mode": "Excluded (Post-Outcome Treatment)",
        "leakage_status": "PROHIBITED in Diabetes Model",
        "icmr_equivalent": "v36 (Diabetes flag)",
        "notes": "Post-outcome drug treatment flag. FORBIDDEN in Diabetes Model."
    },
    {
        "feature_name": "bpq101d_chol_meds",
        "human_name": "Prescribed Cholesterol Medication",
        "source_dataset": "NHANES 2021-2023",
        "source_file": "BPQ_L.xpt",
        "variable": "BPQ101D",
        "type": "Categorical",
        "coverage": "99.9% (N=7,800 adults)",
        "mode": "Excluded (Post-Outcome Treatment)",
        "leakage_status": "PROHIBITED (Post-Outcome Treatment)",
        "icmr_equivalent": "v41 (Dyslipidemia flag)",
        "notes": "Prescription drug treatment flag. Excluded from all models to prevent treatment proxy leakage."
    }
]

df_matrix = pd.DataFrame(matrix_data)
df_matrix.to_csv(AUDIT_OUTPUT_DIR / "model_v2_feature_matrix.csv", index=False)
print(f"Successfully generated revised model_v2_feature_matrix.csv with {len(df_matrix)} features.")
